"""add embedding columns to resume and job

Revision ID: 55783cff139b
Revises: 70af110a30bb
Create Date: 2026-04-22 17:15:37.060647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '55783cff139b'
down_revision: Union[str, Sequence[str], None] = '70af110a30bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add embedding column to user_resume table
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('user_resume', sa.Column('embedding', Vector(384), nullable=True))
    
    # Add embedding column to jobs table
    op.add_column('jobs', sa.Column('embedding', Vector(384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove embedding columns
    op.drop_column('user_resume', 'embedding')
    op.drop_column('jobs', 'embedding')
    # ### end Alembic commands ###
